import mongoose from "mongoose";
import Medicine from "../models/Medicine.js"; // Adjust path if needed

const ayurvedicMedicines = [
  {
    name: "Dabur Chyawanprash",
    price: 315,
    mrp: 350,
    category: "ayurveda",
    symptoms: ["Immunity", "Respiratory Health"],
    description: "Boosts immunity and supports respiratory wellness.",
    stock: 100,
    dosage: "1-2 teaspoons daily",
    prescriptionRequired: "Not Required",
    image: "/images/dabur-chyawanprash.jpg",
    manufacturer: "Dabur India Ltd",
    expiryDate: new Date("2026-12-31"),
  },
  {
    name: "Zandu Kesari Jivan",
    price: 450,
    mrp: 490,
    category: "ayurveda",
    symptoms: ["Energy", "Vitality"],
    description: "Enhances strength and stamina, especially for elders.",
    stock: 80,
    dosage: "1 teaspoon daily",
    prescriptionRequired: "Not Required",
    image: "/images/zandu-kesari.jpg",
    manufacturer: "Zandu Pharmaceuticals",
    expiryDate: new Date("2026-11-30"),
  },
  {
    name: "Baidyanath Chyawanprash Special",
    price: 330,
    mrp: 360,
    category: "ayurveda",
    symptoms: ["Immunity", "General Weakness"],
    description: "Traditional formula for immunity and strength.",
    stock: 90,
    dosage: "1-2 teaspoons daily",
    prescriptionRequired: "Not Required",
    image: "/images/baidyanath-chyawanprash.jpg",
    manufacturer: "Baidyanath",
    expiryDate: new Date("2026-10-15"),
  },
  {
    name: "Patanjali Chyawanprash",
    price: 310,
    mrp: 340,
    category: "ayurveda",
    symptoms: ["Immunity", "Cold & Cough"],
    description: "Ayurvedic blend for seasonal wellness.",
    stock: 120,
    dosage: "1 teaspoon twice daily",
    prescriptionRequired: "Not Required",
    image: "/images/patanjali-chyawanprash.jpg",
    manufacturer: "Patanjali Ayurved",
    expiryDate: new Date("2026-09-30"),
  },
  {
    name: "Himalaya Chyawanprash",
    price: 320,
    mrp: 350,
    category: "ayurveda",
    symptoms: ["Immunity", "Respiratory Health"],
    description: "Supports immune function and lung health.",
    stock: 110,
    dosage: "1 teaspoon daily",
    prescriptionRequired: "Not Required",
    image: "/images/himalaya-chyawanprash.jpg",
    manufacturer: "Himalaya Wellness",
    expiryDate: new Date("2026-08-31"),
  },
  {
    name: "Dabur Giloy Ki Ghanvati",
    price: 180,
    mrp: 200,
    category: "ayurveda",
    symptoms: ["Fever", "Immunity"],
    description: "Giloy tablets for fever and immune support.",
    stock: 150,
    dosage: "1 tablet twice daily",
    prescriptionRequired: "Not Required",
    image: "/images/dabur-giloy.jpg",
    manufacturer: "Dabur India Ltd",
    expiryDate: new Date("2026-07-31"),
  },
  {
    name: "Baidyanath Giloy Juice",
    price: 160,
    mrp: 180,
    category: "ayurveda",
    symptoms: ["Fever", "Detox"],
    description: "Natural detoxifier and immunity booster.",
    stock: 130,
    dosage: "15-20 ml daily",
    prescriptionRequired: "Not Required",
    image: "/images/baidyanath-giloy.jpg",
    manufacturer: "Baidyanath",
    expiryDate: new Date("2026-06-30"),
  },
  {
    name: "Patanjali Giloy Juice",
    price: 150,
    mrp: 170,
    category: "ayurveda",
    symptoms: ["Fever", "Immunity"],
    description: "Supports immune health and reduces fever.",
    stock: 140,
    dosage: "15 ml twice daily",
    prescriptionRequired: "Not Required",
    image: "/images/patanjali-giloy.jpg",
    manufacturer: "Patanjali Ayurved",
    expiryDate: new Date("2026-05-31"),
  },
  {
    name: "Zandu Giloy Capsule",
    price: 170,
    mrp: 190,
    category: "ayurveda",
    symptoms: ["Fever", "Immunity"],
    description: "Capsules for immune support and fever relief.",
    stock: 100,
    dosage: "1 capsule twice daily",
    prescriptionRequired: "Not Required",
    image: "/images/zandu-giloy.jpg",
    manufacturer: "Zandu Pharmaceuticals",
    expiryDate: new Date("2026-04-30"),
  },
  {
    name: "Himalaya Guduchi Tablet",
    price: 190,
    mrp: 210,
    category: "ayurveda",
    symptoms: ["Immunity", "Inflammation"],
    description: "Guduchi tablets for immune modulation.",
    stock: 90,
    dosage: "1 tablet daily",
    prescriptionRequired: "Not Required",
    image: "/images/himalaya-guduchi.jpg",
    manufacturer: "Himalaya Wellness",
    expiryDate: new Date("2026-03-31"),
  },
];

mongoose
  .connect("mongodb://localhost:27017/mediq", {
    useNewUrlParser: true,
    useUnifiedTopology: true,
  })
  .then(async () => {
    await Medicine.deleteMany({ category: "ayurveda" });
    await Medicine.insertMany(ayurvedicMedicines);
    console.log("✅ Ayurvedic medicines seeded successfully");
    mongoose.disconnect();
  })
  .catch((err) => {
    console.error("❌ Seeding error:", err.message);
    mongoose.disconnect();
  });
